### ISSUE TITLE
Reading files from a directory 

### ISSUE THREAD

**Issue by Zingcekhusta** [iparaskev/simple-blink-detector#1]
I have a problem in using color images from a folder not from the dataset file. this is the following error i get when i train my network : 
ValueError: Error when checking input: expected conv2d_73_input to have shape (34, 26, 1) but got array with shape (34, 26, 3)

**Comment by iparaskev** [comment]
You have this problem because the images in the dataset are grayscale so the last dim is 1. I added a variable dims which you can modify to your images dimensions. I think you are using rgb images so dims must be 3.
