### ISSUE TITLE
dataset.csv file

### ISSUE THREAD

**Issue by y0ungchoi** [iparaskev/simple-blink-detector#2]
Hi, Iparaskev,

I appreciate your high-quality data.
But I wonder how did you make dataset.csv with images.
I want to make a dataset with my pictures like your dataset.csv.
please kindly reply me 

Thanks,
Emily

**Comment by iparaskev** [comment]
Hello emily,

It's quite simple. I just used numpy's flatten method to make a vector from every image. And I wrote to the csv file using python's csv module. Sorry for the delayed answer, I hadn't see the issue.

Iasonas
